name: fastapi CICD

# 觸發條件
on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [main]
    types: [closed]

# 執行一項或多項任務
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # 建立環境
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r ./requirements.txt
  
    # 寫入環境變數
    - name: Create env file
      working-directory: ./backend
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    # 建立測試，之後可以寫個 unit-test
    - name: Run Tests
      working-directory: ./backend
      run: |
        ENTRYPOINT="python -m pytest --cov=backend --html=test/report/report.html -W ignore::DeprecationWarning"
        docker build -t pytest-runner .
  
    # 遠端部署
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: |

          cd /home/freegcp0001/gitops/backend
          git config --global user.email "luwenkai0820@gmail.com"
          git config --global user.name "BOBO-LU"
          git pull https://github.com/BOBO-LU/gitops.git
          cd /home/freegcp0001/gitops
          docker-compose up --build -d


